### ISSUE TITLE
Verifying discord account throws error

### ISSUE THREAD

**Issue by madvas** [district0x/StreamTide#10]
Not sure what's going on here, just tried to verify discord account, always throws error after I click Authorize in the pop up window. Not trying anything out of ordinary, using my real discord account.

![image](https://github.com/district0x/StreamTide/assets/3857155/75447a31-d4be-4623-9549-d38466840fb3)

**Comment by ginesdt** [comment]
This wasn't properly set up. It should be working now. Also, error messages have been improved so they give more information on what did exactly fail.
