### ISSUE TITLE
Currency as a Select Box is not necessary

### ISSUE THREAD

**Issue by madvas** [district0x/StreamTide#11]
Since we're gonna support just one currency for donations, making it as a select box is not necessary, since it's causing weird looking UI. 

![image](https://github.com/district0x/StreamTide/assets/3857155/8d11343e-4de3-48ab-a62b-5ea68f7bb032)

**Comment by ginesdt** [comment]
This has been fixed here: https://github.com/district0x/StreamTide/commit/a340b4c06484c1b59c5a1af3ffd21f4caa903968
