### ISSUE TITLE
Native Select Box Options not readable

### ISSUE THREAD

**Issue by madvas** [district0x/StreamTide#8]
Looks like it's white font color on the white background for selectbox options. I'm using Chrome in Windows. This is in night mode UI. Day mode is ok, font is black on white bg. 

![image](https://github.com/district0x/StreamTide/assets/3857155/2e040d0b-384a-42c8-872e-a4e48a46e3e5)

![image](https://github.com/district0x/StreamTide/assets/3857155/c5640637-0612-4718-9863-f01eb1c7738a)

**Comment by ginesdt** [comment]
Using the native `select` component does not allow to customize much the background color and it depends a lot on the OS. To fix this, we are using instead a custom select component.
Fixed in: 
https://github.com/district0x/StreamTide/commit/a340b4c06484c1b59c5a1af3ffd21f4caa903968
